name: cd-for-calculator-api
run-name: ${{ github.actor }} is running the deployment workflow.
on: [push]
# on:
#   pull_request:
#     branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        node-version: ["20"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4
      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v2.1.0
        with:
          publish-dir: "./"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.CICD_CALC_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      # path: /home/runner/work/js_cicd_calculator/js_cicd_calculator
      # download necessary with netlify?
