name: cicd-workflow
run-name: ${{ github.actor }} is running the CI/CD workflow.
on: [push]
# on:
#   pull_request:
#     branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        node-version: ["20"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4

      - name: Initialise branch
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: View Repository
        run: pwd && ls
      - name: SSH link to AWS
        run: echo ${{ secrets.AMAZON_HOST }} > privatekey && chmod 400 privatekey && ls -l privatekey && ssh -i privatekey ec2-user@ec2-13-40-155-48.eu-west-2.compute.amazonaws.com

      # - name: Deploy to EC2
      #   run: |
      #     echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      #     ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
      # - name: View Directory
      #   run: ls -al
      # - name: Zip Repository
      #   run: zip -r js_cicd_calculator . -x "*node_modules*/*"
      # - name: SCP Deployment
      #   uses: srueda99/scp-action@v12
      #   with:
      #     host: ${{secrets.AMAZON_HOST}}
      #     username: ${{secrets.AMAZON_USER}}
      #     key: ${{secrets.AMAZON_SSH}}
      #     destination: "/Home/ec2-user/test"
