name: cicd-workflow
run-name: ${{ github.actor }} is running the CI/CD workflow.
on: [push]
# on:
#   pull_request:
#     branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        node-version: ["20"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4
      - name: Initialise branch
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: View Repository
        run: pwd && ls
      - name: View Directory
        run: ls -al
      # - name: Zip Repository
      #   run: zip -r js_cicd_calculator . -x "*node_modules*/*"
      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/ --exclude=node_modules
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AMAZON_HOST }}
          username: ${{ secrets.AMAZON_USER }}
          key: ${{ secrets.AMAZON_SSH }}
          port: 22
          source: "deploy.tar"
          target: "/home/ec-user/"
      - name: multiple command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AMAZON_HOST }}
          username: ${{ secrets.AMAZON_USER }}
          key: ${{ secrets.AMAZON_SSH }}
          port: 22
          script: |
            tar xvf /home/deploy.tar
            ls -al build
