name: Deploy the calculator
run-name: ${{ github.actor }} is deploying the calculator API.
on:
  push:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        node-version: ["20"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4
      - name: Initialise branch
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Install packages
        run: npm install
      - name: Run index.ts
        run: node index.ts
